name: Build and Push Docker Image 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/msrabbitmq:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/msrabbitmq:latest

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Validate SSH Key
        run: |
          ssh-keygen -y -f ~/.ssh/id_rsa

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          # Se utiliza 'ec2-user' por defecto para Amazon Linux y << 'EOF' para proteger las variables
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          
          # Iniciar sesión en Docker Hub dentro del servidor EC2
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin
          
          # Descargar la versión más reciente de la imagen
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/msrabbitmq:latest
          
          # Detener y remover el contenedor anterior si ya existe
          docker stop msrabbitmq || true
          docker rm msrabbitmq || true
          
          # Ejecutar el nuevo contenedor con tus configuraciones y volumen EFS
          docker run -d \
            --name msrabbitmq \
            -p 8080:8081 \
            --restart unless-stopped \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }} \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            -v /home/ec2-user/efs:/app/efs \
            ${{ secrets.DOCKERHUB_USERNAME }}/msrabbitmq:latest
          EOF
